New-Item -ItemType SymbolicLink -Path "F:\Programming\C++.clang-format" -Target "F:\Programming\Environment\common\configs.clang-format"
New-Item -ItemType SymbolicLink -Path "F:\Programming\C++.clang-tidy" -Target "F:\Programming\Environment\common\configs.clang-tidy"
New-Item -ItemType SymbolicLink -Path "F:\Programming\C++.clangd" -Target "F:\Programming\Environment\common\configs.clangd"
New-Item -ItemType SymbolicLink -Path "$HOME.gitconfig" -Target "F:\Programming\Environment\common\configs.gitconfig"
New-Item -ItemType SymbolicLink -Path "$HOME.config\micro\settings.json" -Target "F:\Programming\Environment\common\configs\micro_settings.json"
New-Item -ItemType SymbolicLink -Path "$HOME.config\micro\bindings.json" -Target "F:\Programming\Environment\windows\configs\micro_bindings.json"
New-Item -ItemType SymbolicLink -Path "$env:APPDATA\Code\User\settings.json" -Target "F:\Programming\Environment\common\configs\vs_code_settings.json"
New-Item -ItemType SymbolicLink -Path "$HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1" -Target "F:\Programming\Environment\windows\configs\Microsoft.PowerShell_profile.ps1"
